apiVersion: apps/v1
kind: Deployment
metadata:
  name: run-controller
  namespace: default
  labels:
    app: run-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: run-controller
  template:
    metadata:
      labels:
        app: run-controller
    spec:
      serviceAccountName: run-controller
      containers:
        - name: run-controller
          image: ghcr.io/meshcloud/run-controller:main
          imagePullPolicy: IfNotPresent
          args:
            - -config
            - /app/runner-config.yml
