apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-devops-block-runner
  description: Microservice that runs building block jobs on Azure DevOps Pipelines
  tags:
    - kotlin
spec:
  type: service
  lifecycle: production
  owner: flock-peng
  system: meshStack

