blockrunner:
  version: ${VERSION:dev}
  uuid: ${RUNNER_UUID:d943b032-7836-4fef-a4a0-158817beecf3}
  # This will enable a 20s wait time when blocks are executed and its state is set randomly (50:50) between
  # success and fail. It can be handy for easy local development.
  debugMode: false
  api:
    url: ${RUNNER_API_URL:http://localhost:8080}
  auth:
    username: ${RUNNER_API_USERNAME:bb-api}
    password: ${RUNNER_API_PASSWORD:guest}
    api-key:
      client-id: ${RUNNER_API_CLIENT_ID:}
      client-secret: ${RUNNER_API_CLIENT_SECRET:}
