apiVersion: v1
kind: ServiceAccount
metadata:
  name: run-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: run-controller
  namespace: default
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: run-controller
  namespace: default
subjects:
  - kind: ServiceAccount
    name: run-controller
    namespace: default
roleRef:
  kind: Role
  name: run-controller
  apiGroup: rbac.authorization.k8s.io
