apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-block-runner
  description: Microservice that runs building blocks using Terraform code
  tags:
    - kotlin
spec:
  type: service
  lifecycle: production
  owner: flock-peng
  system: meshStack