FROM golang:1-alpine

RUN export GOPATH=$PWD/gopath
RUN export PATH=$PWD/gopath/bin:$PATH
RUN export CGO_ENABLED=0
RUN export GOOS=linux

RUN mkdir tfrunner
COPY . ./tfrunner/
RUN cd /go/tfrunner && go build -o tfrunner

ENTRYPOINT [ "/bin/sh", "-c", "cp /go/tfrunner/tfrunner /tmp/." ]