apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: manual-block-runner
  description: Microservice that runs building blocks that require manual intervention
  tags:
    - kotlin
spec:
  type: service
  lifecycle: production
  owner: flock-peng
  system: meshStack