apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gitlab-block-runner
  description: Microservice that runs building block jobs on GitLab CI/CD
  tags:
    - kotlin
spec:
  type: service
  lifecycle: production
  owner: flock-peng
  system: meshStack