logging:
  pattern.console: "%yellow(%d{dd-MM-yyyy HH:mm:ss.SSS}) %magenta([%15.15t]) %highlight(%-5level) ${PID:- } %boldCyan(%21(%X{requestId})) %-40.40logger{39} : %msg%n${LOG_EXCEPTION_CONVERSION_WORD:%ex{15}}"
  level:
    ROOT: INFO
    io.meshcloud: INFO

spring:
  main:
    web-application-type: none

blockrunner:
  version: ${VERSION:dev}
  uuid: f4f4402b-f54d-4ab9-93ae-c07e997041e9
  auth:
    username: bb-api
    password: guest
  api:
    url: http://localhost:8080
