timeoutMins: 42
wsTimeoutMins: 43
initTimeoutMins: 44
workingDir: /tmp/runner/wd
tfInstallDir: /tmp/runner/tfbin
api:
  url: http://localhost:4242
  user: user
  password: pass
privateKey: |
  -----BEGIN PRIVATE KEY-----
  MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCrLanLm4Vf0t9C
  CIzZl35CbU1xlYpfxOoJAkpnRBr1H4GgRFtUGgszgN1jrsMCvpvUTTxBF8jYScXT
  DrMntH/SgCRtrSUudPlL0Vfo5VTMO8YM5z7kmoHCUrZSJskuYGFfSqcMy9FYGskt
  XvXJMeOM5OF9XA3NVqKPCZX7LwFApro+egeLG6ICgpgJR7hSsSR7S092y0i+tRj+
  Bv2xTnvCR8GFi/5Gce4tPUg4ab+6J1QyP3iN3mZKNg9y7BxV+NNdLz7pNcfmR2ox
  +KA84RHluZ+AE6UlZBR4aiMCkskuZKClVkAgoMcrqLQjMHtCQZGZrmWWpdVvCdg/
  7R84mRGbAaPkUvszfRqQatPYwKyV5tD/L6FX/e2dZJ840JaqzdLzJT+YcMyP4OiK
  V4YBWYUyMfXqxFsDkfewyOFTj2FUMbFo/oVVUrcfQa48T5YNdGqGF3A+yAuM0CPg
  /UrRU8szyBp3Ia5mOI/g4fejSwFBwXpwg/pzIr+azVjqqD16Woj1GKxsYv1YgBVG
  49a6WxHQCSwcQjzrjIP8qnbLlCFE7YbtmXS1zha7uZToZ1vuVEONkQ6b0Cumxame
  nftOXlph+bn/rJtLHdfsHnsXU/EipAgtPTFJ67JdKJd1E8l6yi3RSfz9T1JZbu9K
  JiriJsDC+K98e2i6P3fJoxZ0uWqh1QIDAQABAoICABjCLwfjA6R7dI0xfWXPcpSb
  CJOAJJZ7fbo12ZscD6Yam34ZxPfiGHKnld3gHhaciR9o2Gk1znfyG6nOO31nrwE8
  RYiTfYg9pP0hV0y5Ns2fa6LcI42fB1ua6QHy2DBcAlltC8JfDHVo0mY8kOI71ATB
  6hdepCRp/nMf2NCO2OiH9PIqZkLpiUJBr0nQVMmpE3S9zM2K04e529aKHlFx35aX
  GFd/ixSXT/K9JV/7c56yJ4xo/7/NRhA/x3ZAzkxlA/U7aycB/1rAQ4zcwBhuGU+X
  zIkSzlUdJ5TPDSdHIdAS/+VKF1Zgys32xa89SOapYyzOO6VRcRBxZRTB8D0YbqI3
  RsjfOPcFXyrHDQtfKdHlKsrMaeMpzIp2Kgvl9I4gtuWX1obb1ROgpHlmb/NxUG9y
  Xg1+NDE69DAPtJZv0dhrSVKIJ80BeT0auxf918dzn2aNVi6UmC+kRZXrHESzyHti
  n/pnh7aJypygb2moDdOLUW0HtIJ0fEdA4/HEJeW0FZjUEVH0vgNGPcIxF8K1bMUF
  CT1iu3clQ3wWRfs7nRRsEYT7SrWAGh4ulmE2jAy/5YaRzjD2Zaj8gCj5/Wi7A1QU
  9+XzjoG3pB6D3jmYOmSu3ePrM7ZHqT+6JGNv6RAvYG3HsSfObLLjWPjlO3n1xgmV
  9toXB4/cevzh/PXeSAdBAoIBAQDVDbhlHuGMe11/WoFWr5dLVjJhO5yDZ3wwYETb
  6vgysflIVxc3mx+ETdu93dcayMT/KVFR/TFBmE9tBgnUyKt1iUU+AnFQDlmwTY+q
  XjaoF2iMMwbY6U7Md6t583jKAgg49sgGhH4xT9pfZwh0QmhQI9TeOk/40uHgy6y8
  litguSLbQzRQ8DI4LTzvFACzIPFSY1sRkFj2Z064kVjz9qkbZvc2rpn/Zao1D+ip
  HasNo+Z+ltlBBEy4ZxqzWdvZS6qS9950DK78yVW4f1ENGB+96WqlHTB75mCFCLO5
  Qgj8SL3LZKLzylMEveoi1+E6+C+EEZB3Rnn24A+K8Lu5P0XlAoIBAQDNrwqFbb8e
  020x9512+TZE7jPAao0P2qC2YRaUKYV4Sf3QKFuQ3Bx1Vwc2ejqvaa7wYBa5wTIh
  jtu7EOSoTg8kaTtKDJ9S8dZXEGPPHL41+vWpW/RsJ+FeI+YzlZNADTJH8F6qUzLF
  L89VU7OQkW8xadPfZWOoIsws7mVEb1Os8QrUKROb+jCr93mpTd75ixhoBkrYjdeE
  Bvu7VxRvmWrvGuI+YG7ATqWh41cPGGQQW+gD4/TibTxW9UoJTN5mzteV95seWQwm
  hE6dKnv300nJEnNhPLR5ZaWH0XlfKSkJDP0FeFz2KQF4pTqTXrFFOyFZwpGuQr5Z
  9lmSW8twoS0xAoIBAQCi6+8KROctyljhPpCRfY0wqyWzfSZexhAN3lBJ7BEIk1iR
  nSe/+fvL7M4RD0eiz8z1Yt8w13GHO7XhJTD3aszTALnWhX+pPJARZf5qxcj+GYh1
  Tb/6t87uRMT4aNsBfzRSe0TS1xa5FttjASNR5EZooj3yAp2NJZZdlOLvA9cADBM/
  oNCs5EFC/DUQjjdKw/JGknvdnoipRK7KLTvcs871iXOaeUKCL3hNQ3EjgfCAacml
  HC3eri8NBKtCY4DfViGGac3O6LQX0s6eW53baYs8avaGdR/SX4WHtfPZw0mjwuyA
  UODblOiPQ7t8EaHGumt7jwLucxJpW0YHdbfYHS6RAoIBAAp8SvAEaULcCmwKsIdZ
  KxAWiKLdi7VsMtc5WdpRx5EbTIopFIns/rJormBzmLxKifWNIHt1wuV9D+yYbt+5
  owH7L1+WByVGWOP1XPE5COVdltp8aph86/tNnzWwAWK5iX+rXFgYh7UPu+UgsD3F
  fEKrn3Z7B7qRk5ES0izL9BsT6rZoJazE82hA5H3iD2TvV14uO/CQQpVjeb/SL6OE
  0bPAzhnZ9qttFvqKyWxmlOtUlB5mp5xHb1ULiiuxNIFPOCRYDBte9MSd6BgRC2LV
  7aQHgcRKQPUTXn3vCt30Djh85gU6XprZ+k45NiQ/JpBd9FRMG/sjQer6KRTSAywJ
  u3ECggEBAK6RByFdhFTvhsxd9hlnW+jZuPKo4gBwm9Gj+EBXlvZZB9fbHuIgVqOy
  nhPwiPVqdAwcZjHNtNSBVbjJKzXztyGSX4K/lUDhfnTK2vPNnhj3D3bEU7dIBrTK
  AFSI9ThVP8BQERI2S3c+hJZfBi4oxl6rrpTQl/bbdZBFlPlxV/UJMHOriIRivXaV
  ZjiAS4OWggKko57sgCq5X52ebB7vXH7lRPCHE9bSVvysjqC2sAHeK4pOMuF6ubBb
  9ArdePKq/Ze/4MZujcSbEN7PQS16fyG/vA/H3pLWr8yNRIqkdnNcQOk/jB5zLUdV
  MRzugUiwGacCjQ3qjkw+nzrITjYPJrM=
  -----END PRIVATE KEY-----
